spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: p@ssword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    url: jdbc:mysql://localhost:3306
    schemas: school
    user: root
    password: p@ssword
